#!/bin/bash

set -e

app_dir=$(realpath "$(dirname "$0")/../")
current_dir=$(realpath "$(dirname "$0")")

# shellcheck disable=1090
source "${app_dir}/bin/utils" # ASCII, ascii_print

# shellcheck disable=1090
source "${current_dir}/utils" # build_db_url, on_build_db_url_error

ascii_print "\n$(date)\n" "cyan"
ascii_print "🚪 Connecting to Database\n" "yellow"

trap 'on_build_db_url_error' ERR
psql_cmd="psql $(build_db_url)"
trap - ERR

sh -c "${psql_cmd}"

printf "%b" "${ASCII["reset"]}"
