#!/bin/bash

set -e

app_dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")/../")
config_filepath="$app_dir/config/db/credentials.json"

# shellcheck disable=1090
source "${app_dir}/bin/utils" # ASCII, ascii_print

function build_db_url() {
  if [[ ! -f "$config_filepath" ]]; then
    exit 1
  fi

  credentals=$(cat "$config_filepath")
  database_host="$(echo "$credentals" | jq -r ".host // empty")"
  database_name="$(echo "$credentals" | jq -r ".name")"
  database_password="$(echo "$credentals" | jq -r ".password")"
  database_port="$(echo "$credentals" | jq -r ".port // empty")"
  database_username="$(echo "$credentals" | jq -r ".username")"

  # Fallbacks
  database_host="${database_host:-localhost}"
  database_port="${database_port:-5432}"

  url="postgres://"
  url+="${database_username}"
  url+=":${database_password}"
  url+="@${database_host}"
  url+=":${database_port}"
  url+="/${database_name}"

  echo -e "${url}"
}

function migration_filename_to_version() {
  echo -e "${1}" |
  awk '{ match($0, /\/([[:digit:]]+).*\.sql$/, arr); print arr[1] }'
}

function on_build_db_url_error() {
  ascii_print "❗ Database config file does not exist.\n" "red"
  ascii_print "Create it using ${config_filepath}.example\n" "yellow"
}
