#!/bin/bash

app_dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")/../")
backtesting_dir="${app_dir}/db/backtesting"

# shellcheck disable=1090,1091
source "${app_dir}/bin/utils" # ASCII, ascii_print

# shellcheck disable=2207
srcs=($(ls "${backtesting_dir}/bin/"))

for src in "${srcs[@]}"; do
  # shellcheck disable=1090,1091
  source "${backtesting_dir}/bin/${src}" # bt_truncate
done

case "${1}" in
  truncate)
    bt_truncate "${@}"

    ;;
  *)
    ascii_print "⌛ BACKTEST\n" "underline" "yellow"
    ascii_print "Description: Run backtest operations\n" "cyan"
    ascii_print "Usage: backtest [COMMAND] [ARGS]\n" "yellow"
    ascii_print "Commands:\n" "yellow"
    ascii_print "  truncate --api-key=<api_key>      Truncate data that will be overwritten by the next backtest.\n" "yellow"
    ;;
esac

printf "%b" "${ASCII["reset"]}"
